sudo: required
language: generic 
services:
    - docker

before_install:
    - docker build -t doors9/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true doors9/react-test npm test

after_success:
    - docker build -t doors9/multi-client -f ./client
    - docker build -t doors9/multi-nginx -f ./nginx
    - docker build -t doors9/multi-server -f ./server
    - docker build -t doors9/multi-worker -f ./worker
  #login to docker hub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#take images and upload to docker hub
    - docker push doors/multi-client
    - docker push doors/multi-nginx
    - docker push doors/multi-server
    - docker push doors/multi-worker
    
