sudo: required
language: generic 
region: "eu-west-2"
app: "multi-docker"
env: "MultiDocker-env"
bucket_name: "arn:aws:s3:::elasticbeanstalk-eu-west-2-442571048432"
bucket_path: docker-multi
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY
services:
    - docker

before_install:
    - docker build -t doors9/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true doors9/react-test npm test

after_success:
    - docker build -t doors9/multi-client ./client
    - docker build -t doors9/multi-nginx ./nginx
    - docker build -t doors9/multi-server ./server
    - docker build -t doors9/multi-worker ./worker
  #login to docker hub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#take images and upload to docker hub
    - docker push doors9/multi-client
    - docker push doors9/multi-nginx
    - docker push doors9/multi-server
    - docker push doors9/multi-worker

